SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID
FROM (SELECT ITEM_ID FROM ITEM_TREE) A
LEFT OUTER JOIN (SELECT DISTINCT(PARENT_ITEM_ID) AS PARENT_ITEM_ID FROM ITEM_TREE) B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID DESC


# SELECT *
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (SELECT ITEM_ID
#                      FROM ITEM_TREE
#                      WHERE ITEM_ID = PARENT_ITEM_ID)


# 3:40~4:04

# 더 이상 업그레이드x
# 최고참. 

# 패런트에 있다는 건 곧 더 강화가 될 여지가 있다는 것 (결과적 사고!!!)
# 계속 순차적 사고를 해버림.