WITH RENTAL_FEES AS (
    SELECT
        A.CAR_ID,
        A.CAR_TYPE,
        FLOOR(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
        ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
    )
      AND A.CAR_TYPE IN ('SUV', '세단')
      AND C.DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM RENTAL_FEES
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
 
-- 풀이 시간: 13:26~13:43 (17분)
-- 겹치는 이력이 하나도 없는 차량을 선택한다.
-- CTE로 요금 계산을 분리하고 FLOOR로 정수 부분만 출력한다.
-- 상세 회고: FEEDBACK_2026-09-22.md
