SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(B.USER_ID)) AS PUCHASED_USERS, 
ROUND(COUNT(DISTINCT(B.USER_ID))/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
-- SQL 문풀전략 알아보기

-- 아 동일인물이 중복되어 계산되었음. 예제케이스를 자세히 보니 알겠네.