SELECT B.HISTORY_ID,
ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE) + 1) * (100 - CASE
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 BETWEEN 7 AND 29
    THEN (SELECT DISCOUNT_RATE 
                            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 BETWEEN 30 AND 89
    THEN (SELECT DISCOUNT_RATE 
                            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90
    THEN (SELECT DISCOUNT_RATE 
                            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
    ELSE 0
END) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID desc