SELECT APNT_NO, C.PT_NAME, C.PT_NO, B.MCDP_CD, B.DR_NAME, APNT_YMD
FROM APPOINTMENT A JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT C ON C.PT_NO = A.PT_NO
WHERE A.APNT_YMD LIKE '2022-04-13%'
AND APNT_CNCL_YN = 'N' 
AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD