-- MySQL 8.0+
-- 회원별 리뷰 수의 최댓값과 같은 모든 회원을 선택한다.
WITH REVIEW_COUNTS AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    WHERE MEMBER_ID IS NOT NULL
    GROUP BY MEMBER_ID
)
SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REVIEW_COUNTS
    WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_COUNTS)
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
