WITH PAY AS (
  SELECT
    REPLACE(SUBSTRING(MEMO, 5), '-', '') AS PHONE,
    COUNT(TX_ID) AS PAY_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
  FROM PAYMENT_LOG
  WHERE MEMO REGEXP '^PAY:010([0-9]{8}|-[0-9]{4}-[0-9]{4})$'
    AND PAID_AT >= '2026-09-01 00:00:00'
    AND PAID_AT < '2026-10-01 00:00:00'
  GROUP BY PHONE
)
SELECT
  A.MEMBER_ID,
  COALESCE(B.PAY_COUNT, 0) AS PAY_COUNT,
  COALESCE(B.TOTAL_AMOUNT, 0) AS TOTAL_AMOUNT
FROM MEMBERS A
LEFT JOIN PAY B
  ON B.PHONE = REPLACE(A.PHONE, '-', '')
ORDER BY TOTAL_AMOUNT DESC, A.MEMBER_ID;
