WITH front_end AS (SELECT SUM(CODE)
                FROM SKILLCODES
                WHERE CATEGORY = 'Front End'),
python AS (SELECT CODE
          FROM SKILLCODES
          WHERE NAME = 'python'),
C AS (SELECT CODE
          FROM SKILLCODES
          WHERE NAME = 'C#')
          
SELECT CASE 
    WHEN SKILL_CODE & (SELECT * FROM front_end) AND SKILL_CODE & (SELECT * FROM python)
    THEN 'A'
    WHEN SKILL_CODE & (SELECT * FROM C) 
    THEN 'B'
    WHEN SKILL_CODE & (SELECT * FROM front_end)
    THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID
